In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading in Data
df = pd.read_csv('2013_County_Health_Rankings_NewYork_Data.csv')
df

,FIPS,State,County,Deaths,YPLL Rate,95% CI - Low,95% CI - High,Z-Score,Sample Size,% Fair or Poor Health,...,Z-Score.26,# Rec Facilities,Rec Facility Rate,Z-Score.27,# Limited Access,% Limited Access,Z-Score.28,# Fast Foods,% Fast Foods,Z-Score.29
0,36000,New York,NaN,177032,5650,5613,5688,NaN,49967.0,15.0,...,NaN,2137,11.0,NaN,481881,2,NaN,15083,45,NaN
1,36001,New York,Albany,2886,6004,5675,6334,0.09,1041.0,13.0,...,-0.79,39,12.8,-0.61,15073,5,0.22,295,47,0.72
2,36003,New York,Allegany,486,5486,4741,6231,-0.55,228.0,14.0,...,-0.22,3,6.1,0.62,1400,3,-0.47,22,39,-0.21
3,36005,New York,Bronx,14316,7481,7327,7635,1.92,2006.0,24.0,...,0.00,46,3.3,1.14,846,0,-1.41,878,63,2.76
4,36007,New York,Broome,2125,6606,6180,7031,0.84,773.0,14.0,...,1.57,22,11.0,-0.27,9555,5,0.16,156,47,0.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,36115,New York,Washington,699,6003,5309,6697,0.09,249.0,17.0,...,0.71,6,9.5,0.00,2514,4,-0.10,38,44,0.40
59,36117,New York,Wayne,1012,6047,5485,6609,0.15,347.0,19.0,...,0.29,5,5.3,0.76,3205,3,-0.29,60,50,1.18
60,36119,New York,Westchester,6886,4441,4286,4597,-1.84,2156.0,11.0,...,-0.07,187,19.7,-1.87,12044,1,-1.01,713,43,0.25
61,36121,New York,Wyoming,421,5532,4729,6334,-0.49,175.0,15.0,...,0.18,4,9.5,0.00,2038,5,0.18,25,48,0.88
62,36123,New York,Yates,279,5485,4463,6507,-0.55,NaN,NaN,...,-0.72,3,11.8,-0.43,121,0,-1.27,10,30,-1.33

In [3]:
# Selecting the columns we only want
select_df = df[['FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36000,NaN,177032,15.0,8.2,0,9743.0,2245437,1285:1
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
...,...,...,...,...,...,...,...,...,...
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1
62,36123,Yates,279,NaN,5.3,0,20.0,2960,8455:1

In [4]:
# Removing the first row that was NaN 
select_df = select_df.dropna(how='all')
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36000,NaN,177032,15.0,8.2,0,9743.0,2245437,1285:1
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
...,...,...,...,...,...,...,...,...,...
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1
62,36123,Yates,279,NaN,5.3,0,20.0,2960,8455:1

In [5]:
select_df.head(60)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36000,NaN,177032,15.0,8.2,0,9743.0,2245437,1285:1
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
5,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1
6,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1
7,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1
8,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1
9,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1
10,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1
11,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1
12,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1
13,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1
14,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1
15,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1
16,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1
17,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1
18,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1
19,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1
20,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1
21,36041,Hamilton,77,NaN,NaN,0,NaN,638,1611:1
22,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1
23,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1
24,36047,Kings,22670,20.0,8.6,0,840.0,358056,2377:1
25,36049,Lewis,263,15.0,6.3,0,35.0,3048,6775:1
26,36051,Livingston,602,10.0,6.1,0,53.0,5353,6534:1
27,36053,Madison,665,14.0,6.7,0,68.0,6645,3498:1
28,36055,Monroe,6666,16.0,8.2,0,358.0,62342,1688:1
29,36057,Montgomery,587,14.0,7.4,0,37.0,5417,3866:1
30,36059,Nassau,10196,12.0,8.0,0,716.0,129594,824:1
31,36061,New York,12753,16.0,8.7,0,420.0,164516,324:1
32,36063,Niagara,2638,14.0,7.8,0,149.0,19991,8328:1
33,36065,Oneida,2661,14.0,8.3,0,142.0,19374,3262:1
34,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,1645:1
35,36069,Ontario,1128,8.0,6.4,0,66.0,9448,2456:1
36,36071,Orange,3310,17.0,7.1,0,280.0,38369,2576:1
37,36073,Orleans,477,20.0,7.4,0,36.0,4497,10715:1
38,36075,Oswego,1316,17.0,7.0,0,110.0,11872,6429:1
39,36077,Otsego,642,14.0,6.9,0,52.0,6158,2705:1
40,36079,Putnam,783,7.0,7.7,0,58.0,8472,1634:1
41,36081,Queens,17170,18.0,8.3,0,780.0,401948,2757:1
42,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,4429:1
43,36085,Richmond,4505,13.0,8.2,0,201.0,39453,2278:1
44,36087,Rockland,2278,12.0,6.7,0,140.0,32426,1031:1
45,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,3291:1
46,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,1692:1
47,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,1961:1
48,36095,Schoharie,330,12.0,7.0,0,22.0,3133,8173:1
49,36097,Schuyler,227,16.0,6.5,0,NaN,1912,4584:1
50,36099,Seneca,361,NaN,5.9,0,34.0,3660,35206:1
51,36101,Steuben,1135,16.0,7.1,0,95.0,10579,3805:1
52,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,1341:1
53,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,4303:1
54,36107,Tioga,494,14.0,7.5,0,38.0,4716,6386:1
55,36109,Tompkins,643,12.0,6.8,0,50.0,9233,1254:1
56,36111,Ulster,1933,11.0,7.6,0,159.0,19515,1232:1
57,36113,Warren,673,13.0,7.1,0,49.0,6469,1729:1
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1

In [6]:
# Removing the row that was NaN 
select_df = select_df.drop(labels=21, axis=0)
select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
0,36000,NaN,177032,15.0,8.2,0,9743.0,2245437,1285:1
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
...,...,...,...,...,...,...,...,...,...
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1
62,36123,Yates,279,NaN,5.3,0,20.0,2960,8455:1

In [7]:
# Removing the row that was NaN
# Also drop First Row (NY State)
select_df = select_df.drop(labels=62, axis=0)
select_df = select_df.drop(labels=0, axis=0)

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
5,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1
6,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1
7,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1
8,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1
9,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1
10,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1
11,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1
12,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1
13,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1
14,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1
15,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1
16,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1
17,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1
18,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1
19,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1
20,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1
22,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1
23,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1
24,36047,Kings,22670,20.0,8.6,0,840.0,358056,2377:1
25,36049,Lewis,263,15.0,6.3,0,35.0,3048,6775:1
26,36051,Livingston,602,10.0,6.1,0,53.0,5353,6534:1
27,36053,Madison,665,14.0,6.7,0,68.0,6645,3498:1
28,36055,Monroe,6666,16.0,8.2,0,358.0,62342,1688:1
29,36057,Montgomery,587,14.0,7.4,0,37.0,5417,3866:1
30,36059,Nassau,10196,12.0,8.0,0,716.0,129594,824:1
31,36061,New York,12753,16.0,8.7,0,420.0,164516,324:1
32,36063,Niagara,2638,14.0,7.8,0,149.0,19991,8328:1
33,36065,Oneida,2661,14.0,8.3,0,142.0,19374,3262:1
34,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,1645:1
35,36069,Ontario,1128,8.0,6.4,0,66.0,9448,2456:1
36,36071,Orange,3310,17.0,7.1,0,280.0,38369,2576:1
37,36073,Orleans,477,20.0,7.4,0,36.0,4497,10715:1
38,36075,Oswego,1316,17.0,7.0,0,110.0,11872,6429:1
39,36077,Otsego,642,14.0,6.9,0,52.0,6158,2705:1
40,36079,Putnam,783,7.0,7.7,0,58.0,8472,1634:1
41,36081,Queens,17170,18.0,8.3,0,780.0,401948,2757:1
42,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,4429:1
43,36085,Richmond,4505,13.0,8.2,0,201.0,39453,2278:1
44,36087,Rockland,2278,12.0,6.7,0,140.0,32426,1031:1
45,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,3291:1
46,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,1692:1
47,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,1961:1
48,36095,Schoharie,330,12.0,7.0,0,22.0,3133,8173:1
49,36097,Schuyler,227,16.0,6.5,0,NaN,1912,4584:1
50,36099,Seneca,361,NaN,5.9,0,34.0,3660,35206:1
51,36101,Steuben,1135,16.0,7.1,0,95.0,10579,3805:1
52,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,1341:1
53,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,4303:1
54,36107,Tioga,494,14.0,7.5,0,38.0,4716,6386:1
55,36109,Tompkins,643,12.0,6.8,0,50.0,9233,1254:1
56,36111,Ulster,1933,11.0,7.6,0,159.0,19515,1232:1
57,36113,Warren,673,13.0,7.1,0,49.0,6469,1729:1
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1

In [8]:
select_df.head(22)

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
5,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1
6,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1
7,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1
8,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1
9,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1
10,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1
11,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1
12,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1
13,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1
14,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1
15,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1
16,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1
17,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1
18,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1
19,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1
20,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1
22,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1
23,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1

In [9]:
# The the year for the dataset
#select_df["Years"] = "2011"
select_df["Years"] = 2013

select_df

,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio,Years
1,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1,2013
2,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1,2013
3,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1,2013
4,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1,2013
5,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1,2013
6,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1,2013
7,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1,2013
8,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1,2013
9,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1,2013
10,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1,2013
11,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1,2013
12,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1,2013
13,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1,2013
14,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1,2013
15,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1,2013
16,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1,2013
17,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1,2013
18,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1,2013
19,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1,2013
20,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1,2013
22,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1,2013
23,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1,2013
24,36047,Kings,22670,20.0,8.6,0,840.0,358056,2377:1,2013
25,36049,Lewis,263,15.0,6.3,0,35.0,3048,6775:1,2013
26,36051,Livingston,602,10.0,6.1,0,53.0,5353,6534:1,2013
27,36053,Madison,665,14.0,6.7,0,68.0,6645,3498:1,2013
28,36055,Monroe,6666,16.0,8.2,0,358.0,62342,1688:1,2013
29,36057,Montgomery,587,14.0,7.4,0,37.0,5417,3866:1,2013
30,36059,Nassau,10196,12.0,8.0,0,716.0,129594,824:1,2013
31,36061,New York,12753,16.0,8.7,0,420.0,164516,324:1,2013
32,36063,Niagara,2638,14.0,7.8,0,149.0,19991,8328:1,2013
33,36065,Oneida,2661,14.0,8.3,0,142.0,19374,3262:1,2013
34,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,1645:1,2013
35,36069,Ontario,1128,8.0,6.4,0,66.0,9448,2456:1,2013
36,36071,Orange,3310,17.0,7.1,0,280.0,38369,2576:1,2013
37,36073,Orleans,477,20.0,7.4,0,36.0,4497,10715:1,2013
38,36075,Oswego,1316,17.0,7.0,0,110.0,11872,6429:1,2013
39,36077,Otsego,642,14.0,6.9,0,52.0,6158,2705:1,2013
40,36079,Putnam,783,7.0,7.7,0,58.0,8472,1634:1,2013
41,36081,Queens,17170,18.0,8.3,0,780.0,401948,2757:1,2013
42,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,4429:1,2013
43,36085,Richmond,4505,13.0,8.2,0,201.0,39453,2278:1,2013
44,36087,Rockland,2278,12.0,6.7,0,140.0,32426,1031:1,2013
45,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,3291:1,2013
46,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,1692:1,2013
47,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,1961:1,2013
48,36095,Schoharie,330,12.0,7.0,0,22.0,3133,8173:1,2013
49,36097,Schuyler,227,16.0,6.5,0,NaN,1912,4584:1,2013
50,36099,Seneca,361,NaN,5.9,0,34.0,3660,35206:1,2013
51,36101,Steuben,1135,16.0,7.1,0,95.0,10579,3805:1,2013
52,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,1341:1,2013
53,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,4303:1,2013
54,36107,Tioga,494,14.0,7.5,0,38.0,4716,6386:1,2013
55,36109,Tompkins,643,12.0,6.8,0,50.0,9233,1254:1,2013
56,36111,Ulster,1933,11.0,7.6,0,159.0,19515,1232:1,2013
57,36113,Warren,673,13.0,7.1,0,49.0,6469,1729:1,2013
58,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1,2013
59,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1,2013
60,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1,2013
61,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1,2013

In [10]:
# Reorganizing the dataset
clean_data = select_df[['Years', 'FIPS', 'County', 'Deaths', '% Fair or Poor Health', '% Low birthweight', 
            'Food Environment Index', '# Driving Deaths', '# Uninsured', 'Mental Health Provider Ratio']]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2013,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,2013,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,2013,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,2013,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
5,2013,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1
6,2013,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1
7,2013,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1
8,2013,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1
9,2013,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1
10,2013,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1
11,2013,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1
12,2013,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1
13,2013,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1
14,2013,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1
15,2013,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1
16,2013,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1
17,2013,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1
18,2013,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1
19,2013,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1
20,2013,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1
22,2013,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1
23,2013,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1
24,2013,36047,Kings,22670,20.0,8.6,0,840.0,358056,2377:1
25,2013,36049,Lewis,263,15.0,6.3,0,35.0,3048,6775:1
26,2013,36051,Livingston,602,10.0,6.1,0,53.0,5353,6534:1
27,2013,36053,Madison,665,14.0,6.7,0,68.0,6645,3498:1
28,2013,36055,Monroe,6666,16.0,8.2,0,358.0,62342,1688:1
29,2013,36057,Montgomery,587,14.0,7.4,0,37.0,5417,3866:1
30,2013,36059,Nassau,10196,12.0,8.0,0,716.0,129594,824:1
31,2013,36061,New York,12753,16.0,8.7,0,420.0,164516,324:1
32,2013,36063,Niagara,2638,14.0,7.8,0,149.0,19991,8328:1
33,2013,36065,Oneida,2661,14.0,8.3,0,142.0,19374,3262:1
34,2013,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,1645:1
35,2013,36069,Ontario,1128,8.0,6.4,0,66.0,9448,2456:1
36,2013,36071,Orange,3310,17.0,7.1,0,280.0,38369,2576:1
37,2013,36073,Orleans,477,20.0,7.4,0,36.0,4497,10715:1
38,2013,36075,Oswego,1316,17.0,7.0,0,110.0,11872,6429:1
39,2013,36077,Otsego,642,14.0,6.9,0,52.0,6158,2705:1
40,2013,36079,Putnam,783,7.0,7.7,0,58.0,8472,1634:1
41,2013,36081,Queens,17170,18.0,8.3,0,780.0,401948,2757:1
42,2013,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,4429:1
43,2013,36085,Richmond,4505,13.0,8.2,0,201.0,39453,2278:1
44,2013,36087,Rockland,2278,12.0,6.7,0,140.0,32426,1031:1
45,2013,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,3291:1
46,2013,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,1692:1
47,2013,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,1961:1
48,2013,36095,Schoharie,330,12.0,7.0,0,22.0,3133,8173:1
49,2013,36097,Schuyler,227,16.0,6.5,0,NaN,1912,4584:1
50,2013,36099,Seneca,361,NaN,5.9,0,34.0,3660,35206:1
51,2013,36101,Steuben,1135,16.0,7.1,0,95.0,10579,3805:1
52,2013,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,1341:1
53,2013,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,4303:1
54,2013,36107,Tioga,494,14.0,7.5,0,38.0,4716,6386:1
55,2013,36109,Tompkins,643,12.0,6.8,0,50.0,9233,1254:1
56,2013,36111,Ulster,1933,11.0,7.6,0,159.0,19515,1232:1
57,2013,36113,Warren,673,13.0,7.1,0,49.0,6469,1729:1
58,2013,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,2013,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,2013,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,2013,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1

In [11]:
#Drop row 50 and 49(NaN)

clean_data = clean_data.drop(labels=49, axis=0)
clean_data = clean_data.drop(labels=50, axis=0)
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2013,36001,Albany,2886,13.0,8.1,0,148.0,25221,1002:1
2,2013,36003,Allegany,486,14.0,7.1,0,55.0,4526,4079:1
3,2013,36005,Bronx,14316,24.0,10.0,0,425.0,205992,3759:1
4,2013,36007,Broome,2125,14.0,7.9,0,109.0,18901,1926:1
5,2013,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,3647:1
6,2013,36011,Cayuga,780,15.0,7.1,0,70.0,8263,11428:1
7,2013,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,6740:1
8,2013,36015,Chemung,1038,22.0,8.6,0,51.0,7539,3553:1
9,2013,36017,Chenango,618,12.0,6.7,0,51.0,5020,10079:1
10,2013,36019,Clinton,818,14.0,7.2,0,70.0,7271,3042:1
11,2013,36021,Columbia,774,14.0,7.7,0,58.0,6714,1703:1
12,2013,36023,Cortland,501,15.0,8.4,0,32.0,4501,3794:1
13,2013,36025,Delaware,619,12.0,7.5,0,60.0,4914,6834:1
14,2013,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,1466:1
15,2013,36029,Erie,10576,14.0,8.2,0,433.0,75216,2251:1
16,2013,36031,Essex,428,10.0,7.8,0,37.0,4075,3276:1
17,2013,36033,Franklin,575,15.0,7.3,0,53.0,6243,4691:1
18,2013,36035,Fulton,656,17.0,7.8,0,53.0,5906,6163:1
19,2013,36037,Genesee,663,13.0,6.4,0,57.0,5614,4621:1
20,2013,36039,Greene,676,9.0,9.6,0,52.0,4892,8193:1
22,2013,36043,Herkimer,718,12.0,6.9,0,57.0,6674,21493:1
23,2013,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,4667:1
24,2013,36047,Kings,22670,20.0,8.6,0,840.0,358056,2377:1
25,2013,36049,Lewis,263,15.0,6.3,0,35.0,3048,6775:1
26,2013,36051,Livingston,602,10.0,6.1,0,53.0,5353,6534:1
27,2013,36053,Madison,665,14.0,6.7,0,68.0,6645,3498:1
28,2013,36055,Monroe,6666,16.0,8.2,0,358.0,62342,1688:1
29,2013,36057,Montgomery,587,14.0,7.4,0,37.0,5417,3866:1
30,2013,36059,Nassau,10196,12.0,8.0,0,716.0,129594,824:1
31,2013,36061,New York,12753,16.0,8.7,0,420.0,164516,324:1
32,2013,36063,Niagara,2638,14.0,7.8,0,149.0,19991,8328:1
33,2013,36065,Oneida,2661,14.0,8.3,0,142.0,19374,3262:1
34,2013,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,1645:1
35,2013,36069,Ontario,1128,8.0,6.4,0,66.0,9448,2456:1
36,2013,36071,Orange,3310,17.0,7.1,0,280.0,38369,2576:1
37,2013,36073,Orleans,477,20.0,7.4,0,36.0,4497,10715:1
38,2013,36075,Oswego,1316,17.0,7.0,0,110.0,11872,6429:1
39,2013,36077,Otsego,642,14.0,6.9,0,52.0,6158,2705:1
40,2013,36079,Putnam,783,7.0,7.7,0,58.0,8472,1634:1
41,2013,36081,Queens,17170,18.0,8.3,0,780.0,401948,2757:1
42,2013,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,4429:1
43,2013,36085,Richmond,4505,13.0,8.2,0,201.0,39453,2278:1
44,2013,36087,Rockland,2278,12.0,6.7,0,140.0,32426,1031:1
45,2013,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,3291:1
46,2013,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,1692:1
47,2013,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,1961:1
48,2013,36095,Schoharie,330,12.0,7.0,0,22.0,3133,8173:1
51,2013,36101,Steuben,1135,16.0,7.1,0,95.0,10579,3805:1
52,2013,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,1341:1
53,2013,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,4303:1
54,2013,36107,Tioga,494,14.0,7.5,0,38.0,4716,6386:1
55,2013,36109,Tompkins,643,12.0,6.8,0,50.0,9233,1254:1
56,2013,36111,Ulster,1933,11.0,7.6,0,159.0,19515,1232:1
57,2013,36113,Warren,673,13.0,7.1,0,49.0,6469,1729:1
58,2013,36115,Washington,699,17.0,7.8,0,66.0,6830,10553:1
59,2013,36117,Wayne,1012,19.0,6.9,0,79.0,9121,15630:1
60,2013,36119,Westchester,6886,11.0,8.4,0,340.0,100338,573:1
61,2013,36121,Wyoming,421,15.0,5.4,0,41.0,3925,42138:1

In [12]:
clean_data.dtypes

Years                             int64
FIPS                              int64
County                           object
Deaths                            int64
% Fair or Poor Health           float64
% Low birthweight               float64
Food Environment Index            int64
# Driving Deaths                float64
# Uninsured                       int64
Mental Health Provider Ratio     object
dtype: object

In [13]:
# Spliting the Mental Health Provider Ratio 
changing = clean_data['Mental Health Provider Ratio'].str.split(':', expand=True)
changing.dtypes

0    object
1    object
dtype: object

In [14]:
# Converting the string into int
changing = changing.astype('int')

In [15]:
# Changing the Mental Health Provider Ratio into a int value
clean_data['Mental Health Provider Ratio'] = changing[1]/changing[0]
clean_data

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2013,36001,Albany,2886,13.0,8.1,0,148.0,25221,0.000998
2,2013,36003,Allegany,486,14.0,7.1,0,55.0,4526,0.000245
3,2013,36005,Bronx,14316,24.0,10.0,0,425.0,205992,0.000266
4,2013,36007,Broome,2125,14.0,7.9,0,109.0,18901,0.000519
5,2013,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,0.000274
6,2013,36011,Cayuga,780,15.0,7.1,0,70.0,8263,0.000088
7,2013,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,0.000148
8,2013,36015,Chemung,1038,22.0,8.6,0,51.0,7539,0.000281
9,2013,36017,Chenango,618,12.0,6.7,0,51.0,5020,0.000099
10,2013,36019,Clinton,818,14.0,7.2,0,70.0,7271,0.000329
11,2013,36021,Columbia,774,14.0,7.7,0,58.0,6714,0.000587
12,2013,36023,Cortland,501,15.0,8.4,0,32.0,4501,0.000264
13,2013,36025,Delaware,619,12.0,7.5,0,60.0,4914,0.000146
14,2013,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,0.000682
15,2013,36029,Erie,10576,14.0,8.2,0,433.0,75216,0.000444
16,2013,36031,Essex,428,10.0,7.8,0,37.0,4075,0.000305
17,2013,36033,Franklin,575,15.0,7.3,0,53.0,6243,0.000213
18,2013,36035,Fulton,656,17.0,7.8,0,53.0,5906,0.000162
19,2013,36037,Genesee,663,13.0,6.4,0,57.0,5614,0.000216
20,2013,36039,Greene,676,9.0,9.6,0,52.0,4892,0.000122
22,2013,36043,Herkimer,718,12.0,6.9,0,57.0,6674,0.000047
23,2013,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,0.000214
24,2013,36047,Kings,22670,20.0,8.6,0,840.0,358056,0.000421
25,2013,36049,Lewis,263,15.0,6.3,0,35.0,3048,0.000148
26,2013,36051,Livingston,602,10.0,6.1,0,53.0,5353,0.000153
27,2013,36053,Madison,665,14.0,6.7,0,68.0,6645,0.000286
28,2013,36055,Monroe,6666,16.0,8.2,0,358.0,62342,0.000592
29,2013,36057,Montgomery,587,14.0,7.4,0,37.0,5417,0.000259
30,2013,36059,Nassau,10196,12.0,8.0,0,716.0,129594,0.001214
31,2013,36061,New York,12753,16.0,8.7,0,420.0,164516,0.003086
32,2013,36063,Niagara,2638,14.0,7.8,0,149.0,19991,0.000120
33,2013,36065,Oneida,2661,14.0,8.3,0,142.0,19374,0.000307
34,2013,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,0.000608
35,2013,36069,Ontario,1128,8.0,6.4,0,66.0,9448,0.000407
36,2013,36071,Orange,3310,17.0,7.1,0,280.0,38369,0.000388
37,2013,36073,Orleans,477,20.0,7.4,0,36.0,4497,0.000093
38,2013,36075,Oswego,1316,17.0,7.0,0,110.0,11872,0.000156
39,2013,36077,Otsego,642,14.0,6.9,0,52.0,6158,0.000370
40,2013,36079,Putnam,783,7.0,7.7,0,58.0,8472,0.000612
41,2013,36081,Queens,17170,18.0,8.3,0,780.0,401948,0.000363
42,2013,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,0.000226
43,2013,36085,Richmond,4505,13.0,8.2,0,201.0,39453,0.000439
44,2013,36087,Rockland,2278,12.0,6.7,0,140.0,32426,0.000970
45,2013,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,0.000304
46,2013,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,0.000591
47,2013,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,0.000510
48,2013,36095,Schoharie,330,12.0,7.0,0,22.0,3133,0.000122
51,2013,36101,Steuben,1135,16.0,7.1,0,95.0,10579,0.000263
52,2013,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,0.000746
53,2013,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,0.000232
54,2013,36107,Tioga,494,14.0,7.5,0,38.0,4716,0.000157
55,2013,36109,Tompkins,643,12.0,6.8,0,50.0,9233,0.000797
56,2013,36111,Ulster,1933,11.0,7.6,0,159.0,19515,0.000812
57,2013,36113,Warren,673,13.0,7.1,0,49.0,6469,0.000578
58,2013,36115,Washington,699,17.0,7.8,0,66.0,6830,0.000095
59,2013,36117,Wayne,1012,19.0,6.9,0,79.0,9121,0.000064
60,2013,36119,Westchester,6886,11.0,8.4,0,340.0,100338,0.001745
61,2013,36121,Wyoming,421,15.0,5.4,0,41.0,3925,0.000024

In [16]:
clean_data.shape

(58, 10)

In [17]:
clean_data.head(60)

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2013,36001,Albany,2886,13.0,8.1,0,148.0,25221,0.000998
2,2013,36003,Allegany,486,14.0,7.1,0,55.0,4526,0.000245
3,2013,36005,Bronx,14316,24.0,10.0,0,425.0,205992,0.000266
4,2013,36007,Broome,2125,14.0,7.9,0,109.0,18901,0.000519
5,2013,36009,Cattaraugus,1035,20.0,7.1,0,84.0,9323,0.000274
6,2013,36011,Cayuga,780,15.0,7.1,0,70.0,8263,0.000088
7,2013,36013,Chautauqua,1515,16.0,7.8,0,113.0,13103,0.000148
8,2013,36015,Chemung,1038,22.0,8.6,0,51.0,7539,0.000281
9,2013,36017,Chenango,618,12.0,6.7,0,51.0,5020,0.000099
10,2013,36019,Clinton,818,14.0,7.2,0,70.0,7271,0.000329
11,2013,36021,Columbia,774,14.0,7.7,0,58.0,6714,0.000587
12,2013,36023,Cortland,501,15.0,8.4,0,32.0,4501,0.000264
13,2013,36025,Delaware,619,12.0,7.5,0,60.0,4914,0.000146
14,2013,36027,Dutchess,2681,11.0,7.0,0,193.0,26251,0.000682
15,2013,36029,Erie,10576,14.0,8.2,0,433.0,75216,0.000444
16,2013,36031,Essex,428,10.0,7.8,0,37.0,4075,0.000305
17,2013,36033,Franklin,575,15.0,7.3,0,53.0,6243,0.000213
18,2013,36035,Fulton,656,17.0,7.8,0,53.0,5906,0.000162
19,2013,36037,Genesee,663,13.0,6.4,0,57.0,5614,0.000216
20,2013,36039,Greene,676,9.0,9.6,0,52.0,4892,0.000122
22,2013,36043,Herkimer,718,12.0,6.9,0,57.0,6674,0.000047
23,2013,36045,Jefferson,1043,14.0,6.9,0,87.0,13077,0.000214
24,2013,36047,Kings,22670,20.0,8.6,0,840.0,358056,0.000421
25,2013,36049,Lewis,263,15.0,6.3,0,35.0,3048,0.000148
26,2013,36051,Livingston,602,10.0,6.1,0,53.0,5353,0.000153
27,2013,36053,Madison,665,14.0,6.7,0,68.0,6645,0.000286
28,2013,36055,Monroe,6666,16.0,8.2,0,358.0,62342,0.000592
29,2013,36057,Montgomery,587,14.0,7.4,0,37.0,5417,0.000259
30,2013,36059,Nassau,10196,12.0,8.0,0,716.0,129594,0.001214
31,2013,36061,New York,12753,16.0,8.7,0,420.0,164516,0.003086
32,2013,36063,Niagara,2638,14.0,7.8,0,149.0,19991,0.000120
33,2013,36065,Oneida,2661,14.0,8.3,0,142.0,19374,0.000307
34,2013,36067,Onondaga,4451,13.0,8.1,0,269.0,45647,0.000608
35,2013,36069,Ontario,1128,8.0,6.4,0,66.0,9448,0.000407
36,2013,36071,Orange,3310,17.0,7.1,0,280.0,38369,0.000388
37,2013,36073,Orleans,477,20.0,7.4,0,36.0,4497,0.000093
38,2013,36075,Oswego,1316,17.0,7.0,0,110.0,11872,0.000156
39,2013,36077,Otsego,642,14.0,6.9,0,52.0,6158,0.000370
40,2013,36079,Putnam,783,7.0,7.7,0,58.0,8472,0.000612
41,2013,36081,Queens,17170,18.0,8.3,0,780.0,401948,0.000363
42,2013,36083,Rensselaer,1654,16.0,7.3,0,103.0,14327,0.000226
43,2013,36085,Richmond,4505,13.0,8.2,0,201.0,39453,0.000439
44,2013,36087,Rockland,2278,12.0,6.7,0,140.0,32426,0.000970
45,2013,36089,St. Lawrence,1297,17.0,7.6,0,88.0,13454,0.000304
46,2013,36091,Saratoga,1912,12.0,6.7,0,132.0,17080,0.000591
47,2013,36093,Schenectady,1518,14.0,8.6,0,62.0,15217,0.000510
48,2013,36095,Schoharie,330,12.0,7.0,0,22.0,3133,0.000122
51,2013,36101,Steuben,1135,16.0,7.1,0,95.0,10579,0.000263
52,2013,36103,Suffolk,13150,12.0,7.6,0,1109.0,150410,0.000746
53,2013,36105,Sullivan,1043,15.0,8.8,0,88.0,10061,0.000232
54,2013,36107,Tioga,494,14.0,7.5,0,38.0,4716,0.000157
55,2013,36109,Tompkins,643,12.0,6.8,0,50.0,9233,0.000797
56,2013,36111,Ulster,1933,11.0,7.6,0,159.0,19515,0.000812
57,2013,36113,Warren,673,13.0,7.1,0,49.0,6469,0.000578
58,2013,36115,Washington,699,17.0,7.8,0,66.0,6830,0.000095
59,2013,36117,Wayne,1012,19.0,6.9,0,79.0,9121,0.000064
60,2013,36119,Westchester,6886,11.0,8.4,0,340.0,100338,0.001745
61,2013,36121,Wyoming,421,15.0,5.4,0,41.0,3925,0.000024

In [18]:
#convert all objects to integer
df = pd.DataFrame(clean_data)
df = df.astype({"FIPS":"int",
                        "Years":"object",
                        "Deaths":"int",
                        "% Fair or Poor Health":"int",
                        "% Low birthweight":"int",
                        "# Driving Deaths":"int",
                        "# Uninsured":"int"})

In [19]:
df.dtypes

Years                            object
FIPS                              int64
County                           object
Deaths                            int64
% Fair or Poor Health             int64
% Low birthweight                 int64
Food Environment Index            int64
# Driving Deaths                  int64
# Uninsured                       int64
Mental Health Provider Ratio    float64
dtype: object

In [20]:
df

,Years,FIPS,County,Deaths,% Fair or Poor Health,% Low birthweight,Food Environment Index,# Driving Deaths,# Uninsured,Mental Health Provider Ratio
1,2013,36001,Albany,2886,13,8,0,148,25221,0.000998
2,2013,36003,Allegany,486,14,7,0,55,4526,0.000245
3,2013,36005,Bronx,14316,24,10,0,425,205992,0.000266
4,2013,36007,Broome,2125,14,7,0,109,18901,0.000519
5,2013,36009,Cattaraugus,1035,20,7,0,84,9323,0.000274
6,2013,36011,Cayuga,780,15,7,0,70,8263,0.000088
7,2013,36013,Chautauqua,1515,16,7,0,113,13103,0.000148
8,2013,36015,Chemung,1038,22,8,0,51,7539,0.000281
9,2013,36017,Chenango,618,12,6,0,51,5020,0.000099
10,2013,36019,Clinton,818,14,7,0,70,7271,0.000329
11,2013,36021,Columbia,774,14,7,0,58,6714,0.000587
12,2013,36023,Cortland,501,15,8,0,32,4501,0.000264
13,2013,36025,Delaware,619,12,7,0,60,4914,0.000146
14,2013,36027,Dutchess,2681,11,7,0,193,26251,0.000682
15,2013,36029,Erie,10576,14,8,0,433,75216,0.000444
16,2013,36031,Essex,428,10,7,0,37,4075,0.000305
17,2013,36033,Franklin,575,15,7,0,53,6243,0.000213
18,2013,36035,Fulton,656,17,7,0,53,5906,0.000162
19,2013,36037,Genesee,663,13,6,0,57,5614,0.000216
20,2013,36039,Greene,676,9,9,0,52,4892,0.000122
22,2013,36043,Herkimer,718,12,6,0,57,6674,0.000047
23,2013,36045,Jefferson,1043,14,6,0,87,13077,0.000214
24,2013,36047,Kings,22670,20,8,0,840,358056,0.000421
25,2013,36049,Lewis,263,15,6,0,35,3048,0.000148
26,2013,36051,Livingston,602,10,6,0,53,5353,0.000153
27,2013,36053,Madison,665,14,6,0,68,6645,0.000286
28,2013,36055,Monroe,6666,16,8,0,358,62342,0.000592
29,2013,36057,Montgomery,587,14,7,0,37,5417,0.000259
30,2013,36059,Nassau,10196,12,8,0,716,129594,0.001214
31,2013,36061,New York,12753,16,8,0,420,164516,0.003086
32,2013,36063,Niagara,2638,14,7,0,149,19991,0.000120
33,2013,36065,Oneida,2661,14,8,0,142,19374,0.000307
34,2013,36067,Onondaga,4451,13,8,0,269,45647,0.000608
35,2013,36069,Ontario,1128,8,6,0,66,9448,0.000407
36,2013,36071,Orange,3310,17,7,0,280,38369,0.000388
37,2013,36073,Orleans,477,20,7,0,36,4497,0.000093
38,2013,36075,Oswego,1316,17,7,0,110,11872,0.000156
39,2013,36077,Otsego,642,14,6,0,52,6158,0.000370
40,2013,36079,Putnam,783,7,7,0,58,8472,0.000612
41,2013,36081,Queens,17170,18,8,0,780,401948,0.000363
42,2013,36083,Rensselaer,1654,16,7,0,103,14327,0.000226
43,2013,36085,Richmond,4505,13,8,0,201,39453,0.000439
44,2013,36087,Rockland,2278,12,6,0,140,32426,0.000970
45,2013,36089,St. Lawrence,1297,17,7,0,88,13454,0.000304
46,2013,36091,Saratoga,1912,12,6,0,132,17080,0.000591
47,2013,36093,Schenectady,1518,14,8,0,62,15217,0.000510
48,2013,36095,Schoharie,330,12,7,0,22,3133,0.000122
51,2013,36101,Steuben,1135,16,7,0,95,10579,0.000263
52,2013,36103,Suffolk,13150,12,7,0,1109,150410,0.000746
53,2013,36105,Sullivan,1043,15,8,0,88,10061,0.000232
54,2013,36107,Tioga,494,14,7,0,38,4716,0.000157
55,2013,36109,Tompkins,643,12,6,0,50,9233,0.000797
56,2013,36111,Ulster,1933,11,7,0,159,19515,0.000812
57,2013,36113,Warren,673,13,7,0,49,6469,0.000578
58,2013,36115,Washington,699,17,7,0,66,6830,0.000095
59,2013,36117,Wayne,1012,19,6,0,79,9121,0.000064
60,2013,36119,Westchester,6886,11,8,0,340,100338,0.001745
61,2013,36121,Wyoming,421,15,5,0,41,3925,0.000024

In [21]:
# Saving the new and cleaned dataset
file_path = "2013_clean_dataset.csv"
clean_data.to_csv(file_path, index=False)